import { expect } from '@wdio/globals'
import { browser } from '@wdio/globals'
import Login from '../pageobjects/login.js'
import Cart from '../pageobjects/cartGettersAndFunctions.js'
import Verify from '../pageobjects/verification.js'

describe('Test should Pass', () => {
    it('should pass', async () => {
    await Login.open()
    await Login.validLogin('standard_user','secret_sauce')
    await Cart.addItems()
    await expect(Verify.ItemCount).toHaveText('3')
    await Cart.goToCart()
    await expect(browser).toHaveUrl('https://www.saucedemo.com/cart.html')
    await Cart.continueShopping()
    await expect(browser).toHaveUrl('https://www.saucedemo.com/inventory.html')
    await Cart.goToCart()
    await expect(browser).toHaveUrl('https://www.saucedemo.com/cart.html')
    await Cart.removeItem()
    await expect(Verify.removedItem).not.toBeExisting()
    await Cart.checkout()
    await expect(browser).toHaveUrl('https://www.saucedemo.com/checkout-step-one.html')
    await Cart.cancel()
    await expect(browser).toHaveUrl('https://www.saucedemo.com/cart.html')
    await Cart.checkout()
    await expect(browser).toHaveUrl('https://www.saucedemo.com/checkout-step-one.html')
    await Cart.firstNameEnter('standard')
    await Cart.continue()
    await expect(Verify.errorMessage).toBeExisting()
    await Cart.firstNameClear()
    await Cart.lastNameEnter('user')
    await Cart.continue()
    await expect(Verify.errorMessage).toBeExisting()
    await Cart.firstNameEnter('standard')
    await Cart.continue()
    await expect(Verify.errorMessage).toBeExisting()
    await Cart.firstNameClear()
    await Cart.lastNameClear()
    await Cart.zipCodeEnter('12345')
    await Cart.continue()
    await expect(Verify.errorMessage).toBeExisting()
    await Cart.firstNameEnter('standard')
    await Cart.continue()
    await expect(Verify.errorMessage).toBeExisting()
    await Cart.firstNameClear()
    await Cart.lastNameEnter('user')
    await Cart.continue()
    await expect(Verify.errorMessage).toBeExisting()
    await Cart.firstNameEnter('standard')
    await expect(browser).toHaveUrl('https://www.saucedemo.com/checkout-step-two.html')
    })
})